version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/node_api/

hooks:
 
  ApplicationStop:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: root
 
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 600
      runas: root
 