version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: List Files
          command: ls -l
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Backend Docker Image
          command: docker build -t backend-app .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
