version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16  # Use an appropriate CircleCI Node.js image
    steps:
      - checkout  # Check out the source code
      - run:
          name: List Files
          command: ls -l
      - run:
          name: Install Dependencies
          command: npm install -g npm@latest --save
      - setup_remote_docker:
          version: 20.10.7  # Ensure a compatible version of Docker is set up
          docker_layer_caching: true  # Optionally enable Docker layer caching for faster builds
      - run:
          name: Build Backend Docker Image
          command: docker build -t backend-app:v1.0 .
          command: docker ps -a
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
