version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16  # Use an appropriate CircleCI Node.js image
    steps:
      - checkout  # Check out the source code
      - run:
          name: Check npm Version
          command: npm --version
      - run:
          name: Set npm prefix
          command: npm config set prefix ~/.npm
      - run:
          name: Update PATH
          command: echo 'export PATH=$HOME/.npm/bin:$PATH' >> $BASH_ENV
      - run:
          name: Source PATH
          command: source $BASH_ENV
      - run:
          name: Install Dependencies
          command: npm install -g npm@8 --save
      - run:
          name: Check npm Version
          command: npm --version
      - run:
          name: List npm Directory
          command: ls -l $HOME/.npm/bin
      - run:
          name: Print PATH
          command: echo $PATH
          
      - setup_remote_docker:
          version: 20.10.7  # Ensure a compatible version of Docker is set up
          docker_layer_caching: true  # Optionally enable Docker layer caching for faster builds
      - run:
          name: Build Backend Docker Image
          command: docker build -t backend-app:v1.0 .
      - run:
          name: Check Docker Image
          command: docker ps -a

  deploy:
    docker:
      - image: circleci/node:16  # Use an appropriate CircleCI Node.js image
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: List of Docker Files
          command: docker ps -a

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
